# これはmods.tomlファイルの例です。modの読み込みに関連するデータが含まれています。
# いくつかの必須フィールド（#mandatory）と、多くのオプションのフィールド（#optional）があります。
# 全体の形式は標準のTOML形式、v0.5.0です。
# このファイルにはいくつかのTOMLリストがあることに注意してください。
# TOML形式の詳細についてはこちらを参照してください: https://github.com/toml-lang/toml
# 読み込むmodローダーのタイプの名前 - 通常のFML @Mod modの場合、javafmlであるべきです
modLoader="javafml" #mandatory
# 該当するmodローダーに一致するバージョン範囲 - 通常のFML @Modの場合、Forgeバージョンになります
loaderVersion="${loader_version_range}" #mandatory これは通常、MinecraftのバージョンごとにForgeによって更新されます。バージョンのリストについてはダウンロードページを参照してください。
# modのライセンス。これは必須のメタデータで、再配布プロパティの理解を容易にします。
# オプションを確認してください: https://choosealicense.com/。All rights reservedがデフォルトの著作権立場であり、ここでもデフォルトです。
license="${mod_license}"
# このmodで問題が発生した場合に人々が参照するURL
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# modが純粋にクライアントサイドでマルチプレイ機能がない場合（専用サーバーやOpen to LANを含む）、
# これをtrueに設定すると、Forgeが正しいdisplayTestを設定し、専用サーバーでのmodの読み込みをスキップします。
#clientSideOnly=true #optional - 存在しない場合、デフォルトはfalseです
# modのリスト - ここで許可される数は個々のmodローダーによって決定されます
[[mods]] #mandatory
# modのmodid
modId="${mod_id}" #mandatory
# modのバージョン番号
version="${mod_version}" #mandatory
# modの表示名
displayName="${mod_name}" #mandatory
# このmodの更新をクエリするURL。JSON更新仕様を参照してください: https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# このmodの「ホームページ」のURL、mod UIに表示されます
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# 表示用のロゴを含むmod JARのルート内のファイル名
#logoFile="examplemod.png" #optional
# mod UIに表示されるテキストフィールド
#credits="" #optional
# mod UIに表示されるテキストフィールド
authors="${mod_authors}" #optional
# Display Testはサーバー接続画面でのmodの表示を制御します
# MATCH_VERSIONは、クライアントとサーバーのバージョンが異なる場合、modが赤いXを引き起こすことを意味します。これはデフォルトの動作で、modにサーバーとクライアントの要素がある場合に選択すべきです。
# IGNORE_SERVER_VERSIONは、modがサーバーに存在するがクライアントにない場合、赤いXを引き起こさないことを意味します。これはサーバー専用modの場合に使用すべきです。
# IGNORE_ALL_VERSIONは、modがクライアントまたはサーバーに存在する場合、赤いXを引き起こさないことを意味します。これは特別なケースで、modにサーバーコンポーネントがない場合にのみ使用すべきです。
# NONEは、modにdisplay testが設定されていないことを意味します。これを自分で設定する必要があります。詳細についてはIExtensionPoint.DisplayTestを参照してください。この値で任意のスキームを定義できます。
# 重要な注意: これはmodがどの環境（CLIENTまたはDEDICATED SERVER）で読み込まれるかの指示ではありません。modはどこにいても読み込まれるべきです（そして何もしないかもしれません！）。
#displayTest="MATCH_VERSION" # 指定がない場合、clientSideOnly=falseの場合はMATCH_VERSIONがデフォルト、clientSideOnly=trueの場合はIGNORE_ALL_VERSIONがデフォルトです（#optional）

# modの説明テキスト（複数行！）（#mandatory）
description='''${mod_description}'''
# 依存関係 - 特定のmodidの依存関係を示すために.を使用します。依存関係はオプションです。
[[dependencies.${mod_id}]] #optional
    # 依存関係のmodid
    modId="forge" #mandatory
    # この依存関係が存在する必要があるかどうか - ない場合、下記のorderingを指定する必要があります
    mandatory=true #mandatory
    # 依存関係のバージョン範囲
    versionRange="${forge_version_range}" #mandatory
    # 依存関係の順序関係 - 依存関係が必須でない場合、BEFOREまたはAFTERが必要です
    # BEFORE - このmodは依存関係の前に読み込まれます
    # AFTER - このmodは依存関係の後に読み込まれます
    ordering="NONE"
    # この依存関係が適用される側 - BOTH、CLIENT、またはSERVER
    side="BOTH"
# 別の依存関係
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    # このバージョン範囲は現在のMinecraftバージョンの最小値を宣言し、次のメジャーバージョンを含まない
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Featuresはゲーム環境の特定のプロパティで、必要とするものを宣言できます。この例では、
# modがGLバージョン3.2以上を必要とすることを宣言しています。他の機能も追加されます。これらは側を認識するので、これを宣言しても
# 例えばサーバーでのmodの読み込みを停止しません。
#[features.${mod_id}]
#openGLVersion="[3.2,)"
